spring:
  application:
    name: demo
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://172.31.82.104:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: group22
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      type: com.zaxxer.hikari.HikariDataSource
      idleTimeout: 60000
      minimumIdle: 2
      maximumPoolSize: 5
      connectionTimeout: 30000
      poolName: commonservice_pool
      connectionTestQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.MySQL8Dialect
      enabled: true
server:
  port: 8080

jwt:
  secret: secret
